name: Create a Draft Release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    name: Test, Build and Release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)

      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "8"
          cache: maven

      - name: Maven Set Version
        run: mvn versions:set -DnewVersion=${{ steps.get_version.outputs.VERSION }} -B --file pom.xml

      - name: Run the Maven verify phase
        run: mvn --batch-mode --update-snapshots verify

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: "${{ steps.get_version.outputs.VERSION }}-release"
          generate_release_notes: true
          draft: true
          prerelease: false
          files: target/key-to-field-transform-${{ steps.get_version.outputs.VERSION }}.jar
