name: Create a PR

on:
  pull_request:
    branches: [main]
    paths-ignore: ["README.md", "LICENSE", "CONTRIBUTING.md"]

jobs:
  test_and_build:
    name: "[PR] Test & Build"
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)

      - uses: actions/checkout@v5

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "8"
          cache: maven

      - name: Maven Set Version
        run: mvn versions:set -DnewVersion=${{ steps.get_version.outputs.VERSION }} -B --file pom.xml

      - name: Run the Maven verify phase
        run: mvn --batch-mode --update-snapshots verify
